### ISSUE TITLE
move the 'edit' functionality in-line with an actionButton

### ISSUE THREAD

**Issue by gofford** [DavidPatShuiFong/DTedit#31]
I'm glad that someone resurrected this package. 

My question: is it possible to make the 'edit' button in-line? I.e., instead of selecting a row and clicking 'edit', there is a column of 'edit' buttons which share the same edit functionality? It sounds trivial, but it's a workflow requirement and our UI guidelines do not allow the row of buttons atop the table.

I've tried simply adding a `showModal()` within the `callback.actionButton` function, but it does not persist. Is there a workaround?

**Comment by DavidPatShuiFong** [comment]
Thanks for your enquiry.

Just checking, other than the 'edit' button being in-line, would your UI guidelines *also* require the 'add' and 'delete' (and maybe 'copy') buttons to be in-line?

**Comment by gofford** [comment]
Hey! thanks. We don't need either the add or delete functionality at all, only the edit. It's unclear to me how entangled the other functional buttons are, but if they are tightly coupled it might just be easier to write something custom for it.

I was just wondering if it was possible with `DTedit` before I go down that route.

**Comment by DavidPatShuiFong** [comment]
Here is an example, using `DTedit`. Originally written in response to a question stackoverflow https://stackoverflow.com/questions/65801228/how-to-use-sparklines-in-dtedit/65844376#65844376

Requires
* `shinyalert` - version 2.0.0 or greater
* `sparkline`
* `DTedit` - current `develop` branch. or `2.2.4`+ when released. As this example depends on a bugfix by @MatthiasHinz

Uses `callback.actionButton`, just as you thought of using, but uses the `shinyalert` modals instead, which will 'persist' even when the the callback is complete. It is possible to access the inputs inside the `shinyalert` modal using the `callback.R` feature of `shinyalert`. This particular example does *no* validity checking of the inputs! It then uses the 'reactive data' features of `DTedit` to update the data from within the `shinyalert` modal.

Using this method requires an acceptance of the appearance of `shinyalert` modals. And more-or-less creating your own input modals, which was previously the responsibility of `DTedit`! Perhaps `DTedit` should be modified so that its 'shiny input generation' capabilities can be accessed from a `shinyalert` modal. But that would require *quite* a bit more development, I think!

Personally, I used `browser()` within this example code a lot to figure just when particular code is being executed, and what kind of variables/inputs are actually available to each of the functions at the time of execution.

```r
library(shiny)
library(DT)
library(magrittr)
library(sparkline)
library(shinyalert) # version 2.0.0
library(DTedit)

table <- data.frame(
  id = c('spark1', 'spark2'),
  spark = c(
    sparkline::spk_chr(values = 1:3, elementId = 'spark1'),
    sparkline::spk_chr(values = 3:1, elementId = 'spark2')
  )
)

table_react <- shiny::reactiveVal(table)
# reactive version of 'table'

server <- function(input, output) {

  my.callback.actionButton <- function(data, row, buttonID) {
    # data - the current copy of 'thedata'
    # row - the row number of the clicked button
    # buttonID - the buttonID of the clicked button

    # in this case, only one action button per row,
    # so no need to pay attention to buttonID

    shinyalert::shinyalert(
      html = TRUE,
      text = shiny::tagList(
        shiny::textInput(
          "sparkvector",
          "List of numbers",
          paste(as.character(1:5), collapse = ", ")
        )
      ),
      showCancelButton = TRUE,
      callbackR = function(x) {
        if (x == TRUE) {
          # only if closed without the 'escape/cancel'
          temp <- table_react()
          temp[row, 2] <- sparkline::spk_chr(
            as.numeric(unlist(strsplit(input$sparkvector, ","))),
            elementId = temp[row, 1]
          )
          table_react(temp)
          # since table_react is a reactive,
          # dtedit will 'react' to the change in table_react
        }
      }
    )
    return(data)
  }

  sparkline_Results <- DTedit::dtedit(
    input, output,
    name = 'sparkline',
    thedata = table_react,
    datatable.rownames = FALSE,
    edit.cols = c("id"), # *not* editing the sparkline column!
    datatable.call = function(...) {
      arguments <- list(...)
      arguments$escape <- 1 # escape only the first column (not the sparkline column)
      do.call(DT::datatable, arguments) %>% # call DT::datatable with modified arguments
        sparkline::spk_add_deps()
    },
    datatable.options = list(
      fnDrawCallback = htmlwidgets::JS('function(){HTMLWidgets.staticRender();}')
    ),
    action.buttons = list(
      myaction = list( # the 'myaction' name is arbitrary
        columnLabel = "Actions",
        buttonLabel = "Edit spark",
        buttonPrefix = "sparky"
      )
    ),
    callback.actionButton = my.callback.actionButton,
    show.delete = FALSE, # remove all the standard editing buttons
    show.update = FALSE,
    show.copy = FALSE,
    show.insert = FALSE
  )

  shiny::observeEvent(
    sparkline_Results$thedata, ignoreInit = TRUE, {
      # update local copy of 'table_react' when DTedit has made an edit
      table_react(sparkline_Results$thedata)
    })
}

ui <- shiny::fluidPage(
  shinyalert::useShinyalert(),
  shiny::h3('Sparkline example'),
  shiny::uiOutput('sparkline')
)

shiny::shinyApp(ui = ui, server = server)
```

**Comment by gofford** [comment]
This is lovely, thank you @DavidPatShuiFong. I'll dig into this a bit more and see if I can adapt this idea to my use-case!
